export const UPDATE_SUGGESTED_VIDEOS  = 'UPDATE_SUGGESTED_VIDEOS'
export const UPDATE_SOCKET            = 'UPDATE_SOCKET'
export const UPDATE_CURRENT_VIDEO     = 'UPDATE_CURRENT_VIDEO'
export const REQUEST_NEXT_VIDEO       = 'REQUEST_NEXT_VIDEO'

export const UPDATE_PLAYLIST          = 'UPDATE_PLAYLIST'
export const ADD_VIDEO                = 'ADD_VIDEO'
export const SELECT_VIDEO             = 'SELECT_VIDEO'
export const REMOVE_VIDEO             = 'REMOVE_VIDEO'
export const INIT_SOCKET              = 'INIT_SOCKET'

export const UPDATE_PLAYER_HEIGHT     = 'UPDATE_PLAYER_HEIGHT'
export const UPDATE_MASTER            = 'UPDATE_MASTER'

export const REQUEST_VOLUME_CHANGE    = 'REQUEST_VOLUME_CHANGE'
export const UPDATE_VOLUME            = 'UPDATE_VOLUME'
export const UPDATE_PLAYER            = 'UPDATE_PLAYER'
export const UPDATE_PLAYER_SUCCESS    = 'UPDATE_PLAYER_SUCCESS'
export const UPDATE_PLAYBACK          = 'UPDATE_PLAYBACK'
export const REQUEST_PLAYBACK_CHANGE  = 'REQUEST_PLAYBACK_CHANGE'
export const REQUEST_PLAYBACK_UPDATE  = 'REQUEST_PLAYBACK_UPDATE'
export const START_SEEKING            = 'START_SEEKING'
export const STOP_SEEKING             = 'STOP_SEEKING'
export const UPDATE_PLAYER_STATE      = 'UPDATE_PLAYER_STATE'
export const PLAY_VIDEO               = 'PLAY_VIDEO'
export const PAUSE_VIDEO              = 'PAUSE_VIDEO'
export const REQUEST_UPDATE_ROOMS     = 'REQUEST_UPDATE_ROOMS'
export const UPDATE_ROOMS             = 'UPDATE_ROOMS'

export const LOGIN_SUCCESS            = 'LOGIN_SUCCESS'
export const LOGIN                    = 'LOGIN'
export const UPDATE_AUTH              = 'UPDATE_AUTH'
export const LOGIN_ERROR              = 'LOGIN_ERROR'
export const LOGIN_ERROR_DISABLE      = 'LOGIN_ERROR_DISABLE'