export const UPDATE_SUGGESTED_VIDEOS  = 'UPDATE_SUGGESTED_VIDEOS'
export const UPDATE_SOCKET            = 'UPDATE_SOCKET'
export const UPDATE_CURRENT_VIDEO     = 'UPDATE_CURRENT_VIDEO'
export const REQUEST_NEXT_VIDEO       = 'REQUEST_NEXT_VIDEO'

export const UPDATE_PLAYLIST          = 'UPDATE_PLAYLIST'
export const ADD_VIDEO                = 'ADD_VIDEO'
export const SELECT_VIDEO             = 'SELECT_VIDEO'
export const REMOVE_VIDEO             = 'REMOVE_VIDEO'
export const INIT_SOCKET              = 'INIT_SOCKET'

export const UPDATE_PLAYER_HEIGHT     = 'UPDATE_PLAYER_HEIGHT'
export const UPDATE_MASTER            = 'UPDATE_MASTER'

export const REQUEST_VOLUME_CHANGE    = 'REQUEST_VOLUME_CHANGE'
export const UPDATE_VOLUME            = 'UPDATE_VOLUME'
export const UPDATE_CLIENT_PLAYBACK   = 'UPDATE_CLIENT_PLAYBACK'
export const UPDATE_SERVER_PLAYBACK   = 'UPDATE_SERVER_PLAYBACK'
export const REQUEST_PLAYBACK_CHANGE  = 'REQUEST_PLAYBACK_CHANGE'